# https://github.com/open-webui/open-webui/blob/main/docker-compose.yaml

volumes:
  storage:

services:

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    # environment:
    #   - OLLAMA_BASE_URL=host.docker.internal:11434
    ports:
      - 3000:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - storage:/app/backend/data
