# https://bitwarden.com/help/install-and-deploy-unified-beta/#using-docker-run
# https://github.com/Haxxnet/Compose-Examples/tree/main/examples/bitwarden
# https://github.com/bitwarden/self-host/tree/main/docker-unified

volumes:
  db:
  logs:
  bitwarden:

services:

  db:
    image: mariadb:10
    container_name: mariadb
    environment:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_RANDOM_ROOT_PASSWORD
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    
  bitwarden:
    image: ghcr.io/bitwarden/self-host:beta
    container_name: app
    env_file:
      - settings.env
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - bitwarden:/etc/bitwarden
      - logs:/var/log/bitwarden
    depends_on:
      - db
    restart: unless-stopped
