# one based
set -g base-index 1
set -g pane-base-index 1

set -g status-position top

# Enable 256 colors
set -g default-terminal "screen-256color"

# Refresh configuration file
bind r source-file ~/.tmux.conf \; display-message "Configuration reloaded."
