# https://hub.docker.com/_/nextcloud/
# https://github.com/Haxxnet/Compose-Examples/tree/main/examples/nextcloud
# https://github.com/nextcloud/docker?tab=readme-ov-file#running-this-image-with-docker-compose

volumes:
  db:
  storage:

services:

  db:
    image: mariadb:lts
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
    volumes:
      - db:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped

  app:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_HOST
    volumes:
      - storage:/var/www/html
    depends_on:
      - redis
      - db
