# docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama

volumes:
  ollama:

services:

  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: unless-stopped
    environment:
    - OLLAMA_CONTEXT_LENGTH=8192
    ports:
    - 11434:11434
    volumes:
      - ollama:/root/.ollama
